using PaymentInvoice.Application.Abstractions;
using PaymentInvoice.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace PaymentInvoice.Infrastructure.Documents;

internal sealed class QuestPdfInvoiceGenerator : IInvoicePdfGenerator
{
    public Task<string> GenerateAsync(Invoice invoice, CancellationToken cancellationToken)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var root = Path.Combine(AppContext.BaseDirectory, "generated-invoices");
        Directory.CreateDirectory(root);

        var filePath = Path.Combine(root, $"{invoice.InvoiceNumber}.pdf");

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(24);
                page.Size(PageSizes.A4);

                page.Header().Column(column =>
                {
                    column.Item().Text("GST Invoice").FontSize(20).Bold();
                    column.Item().Text($"Invoice No: {invoice.InvoiceNumber}");
                    column.Item().Text($"Order ID: {invoice.OrderId}");
                    column.Item().Text($"Dealer ID: {invoice.DealerId}");
                    column.Item().Text($"Date (UTC): {invoice.CreatedAtUtc:yyyy-MM-dd HH:mm:ss}");
                });

                page.Content().PaddingVertical(12).Column(column =>
                {
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("HSN").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Unit Price").Bold();
                            header.Cell().Text("Line Total").Bold();
                        });

                        foreach (var line in invoice.Lines)
                        {
                            table.Cell().Text(line.ProductName);
                            table.Cell().Text(line.HsnCode);
                            table.Cell().Text(line.Quantity.ToString());
                            table.Cell().Text(line.UnitPrice.ToString("0.00"));
                            table.Cell().Text(line.LineTotal.ToString("0.00"));
                        }
                    });

                    column.Item().PaddingTop(16).AlignRight().Column(summary =>
                    {
                        summary.Item().Text($"Subtotal: {invoice.Subtotal:0.00}");
                        summary.Item().Text($"GST ({invoice.GstType}, {invoice.GstRate:0.##}%): {invoice.GstAmount:0.00}");
                        summary.Item().Text($"Grand Total: {invoice.GrandTotal:0.00}").Bold();
                    });
                });

                page.Footer().AlignCenter().Text("Auto-generated by PaymentInvoice service").FontSize(9);
            });
        }).GeneratePdf(filePath);

        return Task.FromResult(filePath);
    }
}
